from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from shlex import join

from .assets import resolve_opencore_path, resolve_recovery_or_installer_path
from .domain import SUPPORTED_MACOS, VmConfig
from .smbios import generate_smbios, model_for_macos


@dataclass
class PlanStep:
    title: str
    argv: list[str]
    risk: str = "safe"

    @property
    def command(self) -> str:
        return join(self.argv)


def build_plan(config: VmConfig) -> list[PlanStep]:
    meta = SUPPORTED_MACOS[config.macos]
    vmid = str(config.vmid)

    recovery_path = _to_iso_ref(resolve_recovery_or_installer_path(config))
    opencore_source = _to_iso_ref(resolve_opencore_path(config.macos))

    steps = [
        PlanStep(
            title="Create VM shell",
            argv=[
                "qm", "create", vmid,
                "--name", config.name,
                "--ostype", "other",
                "--machine", "q35",
                "--bios", "ovmf",
                "--cores", str(config.cores),
                "--memory", str(config.memory_mb),
                "--cpu", "host",
                "--net0", f"virtio,bridge={config.bridge}",
            ],
        ),
        PlanStep(
            title="Apply macOS hardware profile",
            argv=[
                "qm", "set", vmid,
                "--args",
                "-device isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc "
                "-smbios type=2 -device qemu-xhci -device usb-kbd -device usb-tablet "
                "-global nec-usb-xhci.msi=off -global ICH9-LPC.acpi-pci-hotplug-with-bridge-support=off "
                "-cpu host,kvm=on,vendor=GenuineIntel,+kvm_pv_unhalt,+kvm_pv_eoi,+hypervisor,+invtsc",
                "--vga", "std",
                "--tablet", "1",
                "--scsihw", "virtio-scsi-pci",
            ],
        ),
        *_smbios_steps(config, vmid),
        PlanStep(
            title="Attach EFI + TPM",
            argv=[
                "qm", "set", vmid,
                "--efidisk0", f"{config.storage}:0,efitype=4m,pre-enrolled-keys=0",
                "--tpmstate0", f"{config.storage}:0,version=v2.0",
            ],
        ),
        PlanStep(
            title="Create main disk",
            argv=["qm", "set", vmid, "--sata0", f"{config.storage}:{config.disk_gb}"],
        ),
        PlanStep(
            title="Attach OpenCore ISO",
            argv=["qm", "set", vmid, "--ide2", f"{opencore_source},media=cdrom"],
        ),
        PlanStep(
            title="Attach macOS recovery ISO",
            argv=["qm", "set", vmid, "--ide3", f"{recovery_path},media=cdrom"],
        ),
        PlanStep(
            title="Set boot order",
            argv=["qm", "set", vmid, "--boot", "order=ide2;ide3;sata0"],
        ),
        PlanStep(
            title="Start VM",
            argv=["qm", "start", vmid],
            risk="action",
        ),
    ]

    if meta["channel"] == "preview":
        steps.insert(
            0,
            PlanStep(
                title="Preview warning",
                argv=[
                    "echo",
                    f"Notice: {meta['label']} uses preview assets. Verify OpenCore and recovery sources before production use.",
                ],
                risk="warn",
            ),
        )
    return steps


def render_script(config: VmConfig, steps: list[PlanStep]) -> str:
    meta = SUPPORTED_MACOS[config.macos]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Generated by osx-proxmox-next on {now}",
        f"# Target: {meta['label']} (channel={meta['channel']})",
        f"# VMID: {config.vmid}",
        "",
    ]
    for idx, step in enumerate(steps, start=1):
        lines.append(f"echo '[{idx}/{len(steps)}] {step.title}'")
        lines.append(step.command)
        lines.append("")
    return "\n".join(lines)


def _encode_smbios_value(value: str) -> str:
    """Encode commas for Proxmox smbios1 key=value format."""
    return value.replace(",", "%2C")


def _smbios_steps(config: VmConfig, vmid: str) -> list[PlanStep]:
    if config.no_smbios:
        return []
    serial = config.smbios_serial
    smbios_uuid = config.smbios_uuid
    model = config.smbios_model
    if not serial:
        identity = generate_smbios(config.macos)
        serial = identity.serial
        smbios_uuid = identity.uuid
        model = identity.model
        config.smbios_serial = serial
        config.smbios_uuid = smbios_uuid
        config.smbios_model = model
        config.smbios_mlb = identity.mlb
        config.smbios_rom = identity.rom
    if not model:
        model = model_for_macos(config.macos)
    smbios_value = (
        f"uuid={smbios_uuid},"
        f"serial={serial},"
        f"manufacturer=Apple Inc.,"
        f"product={_encode_smbios_value(model)},"
        f"family=Mac"
    )
    return [
        PlanStep(
            title="Set SMBIOS identity",
            argv=["qm", "set", vmid, "--smbios1", smbios_value],
        ),
    ]


def _to_iso_ref(path: Path) -> str:
    if str(path).startswith("/var/lib/vz/template/iso/"):
        return f"local:iso/{path.name}"
    parts = path.parts
    if len(parts) >= 6 and parts[0:3] == ("/", "mnt", "pve") and parts[-2] == "iso":
        storage = parts[3]
        return f"{storage}:iso/{path.name}"
    return str(path)
